# Database
import os
SQLALCHEMY_DATABASE_URI = f'postgresql://{os.environ["PGUSER"]}:{os.environ["PGPASSWORD"]}@{os.environ["PGHOST"]}:5432/{os.environ["PGDATABASE"]}'
del os

# Change this to something long and random
SECRET_KEY = 'c64722a7-b84e-47ec-b4cc-67f18b7b356455c56d04-75bb-428c-866a-b4c972603d087604444e-715a-4f8a-a85d-f5df99fab0aa7ad31403-7883-4ba1-8568-c19608601f7474afb182-2f06-487e-9a0d-90d8f99541419c2a3410-e7a3-451b-8bd1-ffa32782d112b959a74a-bd2d-460f-8edd-1c8607bc4ccb704b4f6b-9030-4975-95d5-89c73fd46e8c'
BASE_URL = 'https://events.cosup.eu'
USE_PROXY = True

DEFAULT_TIMEZONE = 'Europe/Zurich'
DEFAULT_LOCALE   = 'en_GB'

REDIS_CACHE_URL = 'redis://indico-redis:6379/0'
CELERY_BROKER   = 'redis://indico-redis:6379/1'

# Change these emails to something sensible
NO_REPLY_EMAIL = 'no-reply@cosup.eu'
SUPPORT_EMAIL = 'it@cosup.eu'
SMTP_SERVER = ('smtp.zeptomail.eu', 587)
SMTP_LOGIN = 'emailapikey'
SMTP_PASSWORD = 'yA6KbHtauV+lxWtRE0dv1JWKptoyqv85jCq35CrlK8AuL9Doh6E8hRVqINXuJ2bf2YLR4q5VONgSJdq/vN9YKJE9NtRVJpTGTuv4P2uV48xh8ciEYNYgjZqqBLcRFaFMcBolCi43RPkgWA=='
SMTP_USE_TLS = True

ENABLE_ROOMBOOKING = True

LOG_DIR           = '/opt/indico/log'
TEMP_DIR          = '/opt/indico/tmp'
CACHE_DIR         = '/opt/indico/cache'
CUSTOMIZATION_DIR = '/opt/indico/custom'

STORAGE_BACKENDS   = {'default': 'fs:/opt/indico/archive'}
ATTACHMENT_STORAGE = 'default'

# Specify the plugins you need here
PLUGINS = {'previewer_code', 'vc_zoom', 'payment_manual'}
